
import React, { useEffect, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';
import { Users, TrendingUp, DollarSign, Clock } from 'lucide-react';
import { getGymStats } from '../services/geminiService';

const data = [
  { name: 'السبت', value: 40 },
  { name: 'الأحد', value: 30 },
  { name: 'الاثنين', value: 20 },
  { name: 'الثلاثاء', value: 27 },
  { name: 'الأربعاء', value: 18 },
  { name: 'الخميس', value: 23 },
  { name: 'الجمعة', value: 34 },
];

const Dashboard: React.FC = () => {
    const [aiStats, setAiStats] = useState<any[]>([]);

    useEffect(() => {
        const fetchStats = async () => {
            try {
                const stats = await getGymStats();
                setAiStats(stats);
            } catch (e) {
                console.error("Failed to fetch AI stats", e);
            }
        };
        fetchStats();
    }, []);

  return (
    <div className="space-y-8">
      {/* Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard icon={<Users className="text-blue-500" />} label="إجمالي المشتركين" value="١,٢٥٠" trend="+١٢٪" />
        <StatCard icon={<TrendingUp className="text-green-500" />} label="الحضور اليومي" value="٨٥" trend="+٥٪" />
        <StatCard icon={<DollarSign className="text-yellow-500" />} label="الإيرادات الشهرية" value="٤٥,٠٠٠$" trend="+٨٪" />
        <StatCard icon={<Clock className="text-purple-500" />} label="متوسط وقت التمرين" value="٧٥ دقيقة" trend="-٢٪" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Attendance Chart */}
        <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800">
          <h3 className="text-lg font-semibold mb-6">معدل الحضور الأسبوعي</h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={data}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" />
                <YAxis stroke="#94a3b8" />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: '8px' }}
                  itemStyle={{ color: '#fbbf24' }}
                />
                <Bar dataKey="value" fill="#eab308" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Growth Chart */}
        <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800">
          <h3 className="text-lg font-semibold mb-6">نمو الاشتراكات</h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={data}>
                <defs>
                  <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#eab308" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#eab308" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" />
                <YAxis stroke="#94a3b8" />
                <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: '8px' }}
                />
                <Area type="monotone" dataKey="value" stroke="#eab308" fillOpacity={1} fill="url(#colorValue)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* AI Insights (Generated by Gemini) */}
      <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800">
          <h3 className="text-lg font-semibold mb-4 text-yellow-500">تحليلات ذكية بواسطة Nano Banana</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {aiStats.length > 0 ? aiStats.map((stat, i) => (
                  <div key={i} className="bg-slate-800 p-4 rounded-xl border border-slate-700 flex justify-between items-center">
                      <span className="text-slate-300">{stat.label}</span>
                      <span className="text-xl font-bold text-white">{stat.value}%</span>
                  </div>
              )) : (
                  <p className="text-slate-500">جاري تحميل التحليلات...</p>
              )}
          </div>
      </div>
    </div>
  );
};

interface StatCardProps {
  icon: React.ReactNode;
  label: string;
  value: string;
  trend: string;
}

const StatCard: React.FC<StatCardProps> = ({ icon, label, value, trend }) => (
  <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 hover:border-slate-600 transition-colors">
    <div className="flex justify-between items-start mb-4">
      <div className="p-3 bg-slate-800 rounded-xl">{icon}</div>
      <span className={`text-sm font-medium ${trend.startsWith('+') ? 'text-green-500' : 'text-red-500'}`}>
        {trend}
      </span>
    </div>
    <p className="text-slate-400 text-sm mb-1">{label}</p>
    <p className="text-2xl font-bold text-white">{value}</p>
  </div>
);

export default Dashboard;
